### ISSUE TITLE
Durable ?

### ISSUE THREAD

**Issue by gedw99** [buraksezer/olricdb#1]
It would be easy to add a simple badger backing store.

I ask this because this looks like a great redis replacement but without a backing store it's very risky to us.

Maybe however it's intended purely as a cache ? If so then even then a backing store is going to fix warm up times.

**Comment by buraksezer** [comment]
Hello, 

Firstly, thank you for your interest! OlricDB is heavily inspired by Hazelcast and shares the similar goals with it. So durability is not a top-priority but we may implement it someday, if it's worth to build.
